mitre/saf

help/sonarqube_mapper.md
src/commands/convert/sonarqube_mapper.ts
yarn.lock

Adds a wrapper for the SonarQube hdf-converters mapper.
Also an update to https://github.com/mitre/heimdall_tools/issues/124

Add SonarQube Mapper

---

README.md
src/commands/view/heimdall.ts

e.g `bin/run view -f aws_report_better.json red_hat_good.json`

Allow Passing Files to `saf view`

---

README.md
src/commands/convert/hdf2asff.ts
src/utils/global.ts

Add HDF2ASFF Mapper

---

package-lock.json
src/commands/view/summary.ts
test/sample_data/zap/zap-webappsecurity-hdf.json

Support multiple input files for `saf view:summary`

---

README.md

To include generating InSpec validation code and setting pipeline thresholds.

Clarify Generate README goal

---

src/commands/convert/nessus2hdf.ts
src/commands/convert/snyk2hdf.ts

Remove duplicate JSON suffixes from Nessus and Snyk outputs

---

README.md
package-lock.json
src/commands/generate/xccdf2inspec_stub.ts

Support using STIG ID (version) as InSpec control ID

---

package-lock.json
package.json
src/commands/generate/spreadsheet2inspec_stub.ts
src/commands/generate/xccdf2inspec_stub.ts
src/utils/ckl2poam.ts
test/sample_data/nikto/nikto-hdf.json

Update Heimdall Pacakges to v2.6.19

---

src/utils/xccdf2inspec.ts

Split xccdf2inspec_stub lines by spaces, remove duplicate newlines

---

src/commands/generate/xccdf2inspec_stub.ts

Handle Undefined Fix ID, Check/Fix as Strings Instead of Objects

---

src/commands/generate/spreadsheet2inspec_stub.ts
src/commands/generate/xccdf2inspec_stub.ts
src/utils/ckl2poam.ts

Caused by updates in [271fe808a78179c01938368e46a55335447ad0d1](https://github.com/mitre/heimdall2/commit/271fe808a78179c01938368e46a55335447ad0d1).

Fix CCI to NIST 800-53 Lookup 

---

src/commands/convert/ckl2POAM.ts

Signed-off-by: charleshu-mitre <chu@mitre.org>

Added Source Identifying Vulnerability field to POAM file

---

src/commands/emasser/get/artifacts.ts
src/commands/emasser/get/dashboards.ts
src/commands/emasser/get/milestones.ts
src/commands/emasser/get/poams.ts
src/commands/emasser/get/roles.ts
src/commands/emasser/get/workflow_instances.ts

fixed the static args parameter being used in the emasser command to match the syntax from the oclif version bump
Signed-off-by: Amndeep Singh Mann <amann@mitre.org>

fixed the static args parameter

---

.github/workflows/push-to-docker-main.yml
.github/workflows/push-to-docker.yml
.github/workflows/test-docker-image.yml

added multiplatform support, updated versions of actions in those specific workflows
finishes the loop with https://github.com/mitre/heimdall2/pull/4100

added multiplatform support

---

.github/workflows/push-to-docker.yml
.github/workflows/push-to-npm-gpr.yml

Signed-off-by: wdower <will@dower.dev>

resolves #1492

---

README.md

Based on feedback provided in previously merged PR: https://github.com/mitre/saf/pull/1160#discussion_r1240244981

Update ReadMe Header section name based on feedback in PR#1160

---

.vscode/launch.json
package-lock.json
src/commands/view/summary.ts
src/utils/ohdf/calculations.ts
src/utils/ohdf/dataLoader.ts
src/utils/ohdf/outputGenerator.ts
src/utils/ohdf/types.ts
test/sample_data/utils/ohdf/calculations/calculateComplianceScoresForExecJSONs.sample
test/sample_data/utils/ohdf/calculations/calculateSeverityCounts.sample
test/sample_data/utils/ohdf/calculations/calculateSummariesForExecJSONs.sample
test/sample_data/utils/ohdf/calculations/calculateTotalCounts.sample
test/sample_data/utils/ohdf/calculations/calculateTotalCountsForSummaries.sample
test/utils/ohdf/calculations.test.ts
test/utils/ohdf/dataloader.test.ts

Refactored my first PR to better break apart code responsibility and added tests

---

README.md
package.json
src/commands/generate/update_controls4delta.ts

Allow controls to be renamed based on XCCDF Group Id

Add flag to update_controls4delta to rename controls

---

README.md
docs/contributors-guide.md
package.json

Update README.md to link to developers page

---

src/commands/generate/inspec_profile.ts
test/commands/convert/ckl2hdf.test.ts
test/commands/convert/ckl2poam.test.ts

Add a test to check the ckl2poam command

Add ckl2POAM test

---

LICENSE
README.md

license and notice clarification
